[master]
devops-master ansible_host=172.31.19.182 ansible_user=ubuntu ansible_connection=local

[agent]
devops-agent ansible_host=ip-172-31-24-49.ec2.internal 

[all:vars]
ansible_python_interpreter=/usr/bin/python3
